Homework1
made-ml-in-prod-2021/lakuzne4 pull request #2
Opened 2021-05-16 19:49 UTC by lakuzne4

Добрый день! Прошу провести code review на первое задание по курсу "Машинное обучение в продакшене"

2021-05-23 15:34 UTC, ol-ga-00 reviewed
В ml_project/ml_project нужно положить только код, конфигурационные файлы необходимо оттуда вынести. Также оттуда нужно вынести README.md и requirements.txt

2021-05-23 15:34 UTC, ol-ga-00 commented on ml_project/ml_project/train_pipeline.py
> +sys.path.append(r"D:\MADE_homeworks\ML_prod\homework1_repo\ml_project")  # for developing
У меня такого пути нет
Попробуйте использовать не абсолютный, а относительный путь

2021-05-23 15:34 UTC, ol-ga-00 commented on ml_project/ml_project/train_pipeline.py
> +            filename=r'D:\MADE_homeworks\ML_prod\homework1_repo\ml_project\ml_project\logs\logs.txt'
У меня такого пути нет
Попробуйте использовать не абсолютный, а относительный путь

2021-05-23 15:35 UTC, ol-ga-00 requested changes
Относительно тестов рекомендую использовать conftest.py, и в фикстурах указывать scope 
https://habr.com/ru/post/448786/

2021-05-29 11:42 UTC, lakuzne4 commented
Поменял структуру тестов, сделал относительные импорты (без абсолютных путей), добавил conftest.py, убрал лишние файлы конфигов/reports/logs из отслеживаемых git.

2021-05-30 19:51 UTC, ol-ga-00 commented
> Поменял структуру тестов, сделал относительные импорты (без абсолютных путей), добавил conftest.py, убрал лишние файлы конфигов/reports/logs из отслеживаемых git.

Пропали конфигурационные файлы, прошу их вернуть!
А также всё ещё неправильная структура проекта: вынесите содержимое ml_project/ml_project на уровень выше

2021-05-30 19:54 UTC, ol-ga-00 requested changes
> Поменял структуру тестов, сделал относительные импорты (без абсолютных путей),  добавил conftest.py, убрал лишние файлы конфигов/reports/logs из отслеживаемых git.

Пропали конфигурационные файлы, прошу их вернуть!
А также всё ещё неправильная структура проекта: вынесите содержимое ml_project/ml_project на уровень выше

2021-05-31 12:46 UTC, lakuzne4 commented
Вернул configs, сделал плоскую структуру проекта, добавил пустые .gitkeep для отображения всех папок. Основной файл train_pipeline.py лежит в корне ml_project, остальной код в source_code.

2021-06-01 15:45 UTC, ol-ga-00 approved these changes
30 * 0.65 = 19.5

Ставлю 19.5 баллов

2021-06-03 15:06 UTC, ol-ga-00 commented
@lakuzne4, если у вас нет вопросов по этой домашней работе, то предлагаю произвести merge

2021-06-03 15:11 UTC, merged

2021-06-03 15:11 UTC, lakuzne4 commented
сделал merge и закрыл, спасибо)